apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: gitops-development
  namespace: argocd
spec:
  project: default
  source:
   repoURL: https://github.com/MMSaad/gitops
   path: helm
   targetRevision: HEAD
   helm:
    valuesFiles:
     values.yaml
  destination:
   server: https://kubernetes.default.svc
   namespace: gitops-development
  syncPolicy:
   automated: {}